[package]
name = "xmpp-client"
version = "0.1.0"
description = "A work in progress xmpp lib"
license = "MPL-2.0"
authors = ["Freyskeyd <simon.paitrault@gmail.com>"]

[dependencies]
bytes = "0.4"
futures = "0.1"
tokio-io = "0.1.1"
tokio-core = "0.1"
tokio-tls = "0.1"
native-tls = "0.1"
base64 = "0.4.0"

[dependencies.xmpp-proto]
path = "../proto"

