[package]
name = "xmpp-client"
version = "0.1.0"
description = "A work in progress xmpp lib"
license = "MPL-2.0"
authors = ["Freyskeyd <simon.paitrault@gmail.com>"]

[dependencies]
bytes = "0.4"
futures = "*"
tokio-io = "*"
tokio-core = "*"
tokio-tls = "*"
native-tls = "*"
base64 = "0.4.0"
sasl = "0.3.0"
log = "^0.3"

[dev-dependencies]
env_logger = "^0.4"

[dependencies.xmpp-proto]
path = "../proto"

