sudo: true
language: rust
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly
cache: cargo
before_script:
- command -v cargo-coveralls > /dev/null 2>&1 || cargo install cargo-travis
- export PATH=$HOME/.cargo/bin:$PATH
script: cargo build --all --verbose && cargo test --all --verbose
after_success:
- test $TRAVIS_RUST_VERSION = "stable" && cargo coveralls --all --verbose
- |
  [ $TRAVIS_BRANCH = doc_doc ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  cargo doc &&
  echo "<meta http-equiv=refresh content=0;url=xmpp/index.html>" > target/doc/index.html &&
  sudo pip install ghp-import &&
  ghp-import -n target/doc &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - binutils-dev
    - cmake
    sources:
    - kalakris-cmake
env:
  global:
    secure: ROxFwof0HdZZOOvJ8dmQmat9051hKIUTaNV7YFtkVJUYK47Rv6bHMosjVbUh5cGaM0QlQH67x0sdH3hexJtp5clsl4PSo6LOuEEQPTRg5nxX4mtA3m6Ic0yLOAI+zyCg59pybD1aJHG/XSdfKjmJ6hHrh1N1jdd5FWiNJ7dv5UtXTXjHqdGQ1HfIcZomMJD23C/PXOt0r5BJgqKGnTYYqJsDZe62P2cCPkAfG79SP47oaKyNE+jG0cmoqsZpMRrq5QLI+mFhXZMXDZCe7lJXP98yKaM/RUE/bxic1N0d0KWwTfSyMfKZAe4cJl5Z+HETUITeZtTfflMECDT/yKu2aFs3LYqqzIM3zPEojW1PAhVpYq9aKZu/Wf3/mOa8/MthLXNHd4R8zeENjDaKwVMkbmUzWnrwMbqwq5BdvQZKH0b47f3Ne7oXBCnSXX5dZkLH5gl2JbjfsytL4H6a/KAQEiLyeflQOAUiijB4pOQOpHhsM4BaGWcBh/Qral9p8tWdJWuiw/0Ep/ziUgwIq7uJ1j1JTkbQQF3MKGccdISMHQp+zzN9ix2Hyy/W+PRsMVhb7+r36NpIs8/IHsxHVNNH8BeVKZz+XD1uHwuJnWndMJS4Pok5r3ZNy+uA3E00WfcsKzHa5RgyqsW74NvUnOj8TCI0eBdGLH+y+8WwW1+j1uM=
