ejabberd:
  image: rroemhild/ejabberd
  ports:
    - 5222:5222
    - 5269:5269
    - 5280:5280
  environment:
    - ERLANG_NODE=ejabberd
    - XMPP_DOMAIN=example.com xyz.io
    # - EJABBERD_ADMINS=admin@example.com
    - EJABBERD_USERS=simon@example.com:test user1@xyz.io
