ejabberd:
  image: rroemhild/ejabberd
  ports:
    - 5222:5222
    - 5269:5269
    - 5280:5280
  volumes:
    - ssl:/opt/ejabberd/ssl
  environment:
    - ERLANG_NODE=ejabberd
    - EJABBERD_LOGLEVEL=5
    - XMPP_DOMAIN=example.com
    # - EJABBERD_ADMINS=admin@example.com
    - EJABBERD_USERS=alice@example.com:test user1@example.com:test
