[package]
name = "xmpp-server"
version = "0.1.2"
description = "A work in progress xmpp lib"
license = "MPL-2.0"
documentation = "https://docs.rs/xmpp-server"
authors = ["Freyskeyd <simon.paitrault@gmail.com>"]

[dependencies]
