(function() {var implementors = {};
implementors["bytes"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hasher.html\" title=\"trait core::hash::Hasher\">Hasher</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/collections/hash/map/struct.DefaultHasher.html\" title=\"struct std::collections::hash::map::DefaultHasher\">DefaultHasher</a>",];
implementors["libc"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hasher.html\" title=\"trait core::hash::Hasher\">Hasher</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/collections/hash/map/struct.DefaultHasher.html\" title=\"struct std::collections::hash::map::DefaultHasher\">DefaultHasher</a>",];
implementors["mio"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hasher.html\" title=\"trait core::hash::Hasher\">Hasher</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/collections/hash/map/struct.DefaultHasher.html\" title=\"struct std::collections::hash::map::DefaultHasher\">DefaultHasher</a>",];
implementors["openssl"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hasher.html\" title=\"trait core::hash::Hasher\">Hasher</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/collections/hash/map/struct.DefaultHasher.html\" title=\"struct std::collections::hash::map::DefaultHasher\">DefaultHasher</a>",];
implementors["regex_syntax"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hasher.html\" title=\"trait core::hash::Hasher\">Hasher</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/collections/hash/map/struct.DefaultHasher.html\" title=\"struct std::collections::hash::map::DefaultHasher\">DefaultHasher</a>",];
implementors["serde"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hasher.html\" title=\"trait core::hash::Hasher\">Hasher</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/collections/hash/map/struct.DefaultHasher.html\" title=\"struct std::collections::hash::map::DefaultHasher\">DefaultHasher</a>",];
implementors["siphasher"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hasher.html\" title=\"trait core::hash::Hasher\">Hasher</a> for <a class=\"struct\" href=\"siphasher/sip/struct.SipHasher.html\" title=\"struct siphasher::sip::SipHasher\">SipHasher</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hasher.html\" title=\"trait core::hash::Hasher\">Hasher</a> for <a class=\"struct\" href=\"siphasher/sip/struct.SipHasher13.html\" title=\"struct siphasher::sip::SipHasher13\">SipHasher13</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hasher.html\" title=\"trait core::hash::Hasher\">Hasher</a> for <a class=\"struct\" href=\"siphasher/sip/struct.SipHasher24.html\" title=\"struct siphasher::sip::SipHasher24\">SipHasher24</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hasher.html\" title=\"trait core::hash::Hasher\">Hasher</a> for <a class=\"struct\" href=\"siphasher/sip128/struct.SipHasher.html\" title=\"struct siphasher::sip128::SipHasher\">SipHasher</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hasher.html\" title=\"trait core::hash::Hasher\">Hasher</a> for <a class=\"struct\" href=\"siphasher/sip128/struct.SipHasher13.html\" title=\"struct siphasher::sip128::SipHasher13\">SipHasher13</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hasher.html\" title=\"trait core::hash::Hasher\">Hasher</a> for <a class=\"struct\" href=\"siphasher/sip128/struct.SipHasher24.html\" title=\"struct siphasher::sip128::SipHasher24\">SipHasher24</a>",];
implementors["string_cache"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hasher.html\" title=\"trait core::hash::Hasher\">Hasher</a> for <a class=\"struct\" href=\"siphasher/sip/struct.SipHasher.html\" title=\"struct siphasher::sip::SipHasher\">SipHasher</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hasher.html\" title=\"trait core::hash::Hasher\">Hasher</a> for <a class=\"struct\" href=\"siphasher/sip/struct.SipHasher13.html\" title=\"struct siphasher::sip::SipHasher13\">SipHasher13</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hasher.html\" title=\"trait core::hash::Hasher\">Hasher</a> for <a class=\"struct\" href=\"siphasher/sip/struct.SipHasher24.html\" title=\"struct siphasher::sip::SipHasher24\">SipHasher24</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hasher.html\" title=\"trait core::hash::Hasher\">Hasher</a> for <a class=\"struct\" href=\"siphasher/sip128/struct.SipHasher.html\" title=\"struct siphasher::sip128::SipHasher\">SipHasher</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hasher.html\" title=\"trait core::hash::Hasher\">Hasher</a> for <a class=\"struct\" href=\"siphasher/sip128/struct.SipHasher13.html\" title=\"struct siphasher::sip128::SipHasher13\">SipHasher13</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hasher.html\" title=\"trait core::hash::Hasher\">Hasher</a> for <a class=\"struct\" href=\"siphasher/sip128/struct.SipHasher24.html\" title=\"struct siphasher::sip128::SipHasher24\">SipHasher24</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hasher.html\" title=\"trait core::hash::Hasher\">Hasher</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/collections/hash/map/struct.DefaultHasher.html\" title=\"struct std::collections::hash::map::DefaultHasher\">DefaultHasher</a>",];
implementors["syn"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hasher.html\" title=\"trait core::hash::Hasher\">Hasher</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/collections/hash/map/struct.DefaultHasher.html\" title=\"struct std::collections::hash::map::DefaultHasher\">DefaultHasher</a>",];
implementors["tokio_core"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hasher.html\" title=\"trait core::hash::Hasher\">Hasher</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/collections/hash/map/struct.DefaultHasher.html\" title=\"struct std::collections::hash::map::DefaultHasher\">DefaultHasher</a>",];
implementors["void"] = [];
implementors["xmpp_client"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hasher.html\" title=\"trait core::hash::Hasher\">Hasher</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/collections/hash/map/struct.DefaultHasher.html\" title=\"struct std::collections::hash::map::DefaultHasher\">DefaultHasher</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hasher.html\" title=\"trait core::hash::Hasher\">Hasher</a> for <a class=\"struct\" href=\"siphasher/sip/struct.SipHasher.html\" title=\"struct siphasher::sip::SipHasher\">SipHasher</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hasher.html\" title=\"trait core::hash::Hasher\">Hasher</a> for <a class=\"struct\" href=\"siphasher/sip/struct.SipHasher13.html\" title=\"struct siphasher::sip::SipHasher13\">SipHasher13</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hasher.html\" title=\"trait core::hash::Hasher\">Hasher</a> for <a class=\"struct\" href=\"siphasher/sip/struct.SipHasher24.html\" title=\"struct siphasher::sip::SipHasher24\">SipHasher24</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hasher.html\" title=\"trait core::hash::Hasher\">Hasher</a> for <a class=\"struct\" href=\"siphasher/sip128/struct.SipHasher.html\" title=\"struct siphasher::sip128::SipHasher\">SipHasher</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hasher.html\" title=\"trait core::hash::Hasher\">Hasher</a> for <a class=\"struct\" href=\"siphasher/sip128/struct.SipHasher13.html\" title=\"struct siphasher::sip128::SipHasher13\">SipHasher13</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hasher.html\" title=\"trait core::hash::Hasher\">Hasher</a> for <a class=\"struct\" href=\"siphasher/sip128/struct.SipHasher24.html\" title=\"struct siphasher::sip128::SipHasher24\">SipHasher24</a>",];
implementors["xmpp_proto"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hasher.html\" title=\"trait core::hash::Hasher\">Hasher</a> for <a class=\"struct\" href=\"siphasher/sip/struct.SipHasher.html\" title=\"struct siphasher::sip::SipHasher\">SipHasher</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hasher.html\" title=\"trait core::hash::Hasher\">Hasher</a> for <a class=\"struct\" href=\"siphasher/sip/struct.SipHasher13.html\" title=\"struct siphasher::sip::SipHasher13\">SipHasher13</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hasher.html\" title=\"trait core::hash::Hasher\">Hasher</a> for <a class=\"struct\" href=\"siphasher/sip/struct.SipHasher24.html\" title=\"struct siphasher::sip::SipHasher24\">SipHasher24</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hasher.html\" title=\"trait core::hash::Hasher\">Hasher</a> for <a class=\"struct\" href=\"siphasher/sip128/struct.SipHasher.html\" title=\"struct siphasher::sip128::SipHasher\">SipHasher</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hasher.html\" title=\"trait core::hash::Hasher\">Hasher</a> for <a class=\"struct\" href=\"siphasher/sip128/struct.SipHasher13.html\" title=\"struct siphasher::sip128::SipHasher13\">SipHasher13</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hasher.html\" title=\"trait core::hash::Hasher\">Hasher</a> for <a class=\"struct\" href=\"siphasher/sip128/struct.SipHasher24.html\" title=\"struct siphasher::sip128::SipHasher24\">SipHasher24</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hasher.html\" title=\"trait core::hash::Hasher\">Hasher</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/collections/hash/map/struct.DefaultHasher.html\" title=\"struct std::collections::hash::map::DefaultHasher\">DefaultHasher</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
